import { Link } from 'react-router-dom';
import PageShell from '../components/PageShell';
import PageHero from '../components/PageHero';
import bridge from '../assets/cucutaBGPuente.jpg';
import engineer from '../assets/engineer.jpg';
import people from '../assets/company/personal.jpg';
import vehicles from '../assets/company/camionetas.jpg';
import mixers from '../assets/company/bultos.jpg';
import { company } from '../data/company';

export default function AboutPage() {
  return <PageShell>
    <PageHero eyebrow="Nosotros" image={people} title="Experiencia local, perspectiva de largo plazo." description="DIMELCO S.A.S. desarrolla soluciones de gas, infraestructura, climatización y energía para proyectos que deben operar con seguridad." />
    <section className="section"><div className="container split"><div className="split__image"><img src={engineer} alt="Ingeniero Dimelco en un proyecto" /></div><div className="split__text"><p className="eyebrow eyebrow--green">Quiénes somos</p><h2>Ingeniería que se hace cargo.</h2><p>{company.legalName}, {company.name}, es una empresa colombiana especializada en gases combustibles, climatización y energías alternativas. Diseñamos, construimos, ejecutamos, mantenemos y equipamos proyectos civiles y electromecánicos.</p><p>Con sede en Cúcuta y trayectoria desde 2004, trabajamos para consolidar relaciones de largo plazo con clientes que valoran la calidad, el cumplimiento y el servicio.</p></div></div></section>
    <section className="section section--muted"><div className="container"><div className="section-heading"><p className="eyebrow eyebrow--green">Identidad corporativa</p><h2>Un propósito claro en cada obra.</h2></div><div className="card-grid"><article className="card"><span className="card__number">Misión</span><h3>Liderar ante nuevos retos.</h3><p>Permanecer como líderes en el sector ofreciendo construcción, ejecución, mantenimiento y equipamiento, con talento humano eficaz, eficiente y capacitado para consolidar relaciones a largo plazo.</p></article><article className="card"><span className="card__number">Visión</span><h3>Competir con excelencia.</h3><p>Ser una empresa líder en obras civiles, caracterizada por un equipo comprometido y altos estándares de calidad, cumplimiento y servicio que contribuyan al desarrollo del país.</p></article><article className="card"><span className="card__number">Gerencia</span><h3>{company.manager}</h3><p>Gerente General de DIMELCO S.A.S., responsable de orientar una operación técnica cercana a sus clientes y a las necesidades del territorio.</p></article></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow eyebrow--green">Cómo trabajamos</p><h2>Una forma de hacer que se nota en la entrega.</h2></div><div className="card-grid"><article className="card"><span className="card__number">Responsabilidad</span><h3>Cumplir lo acordado.</h3><p>El logro efectivo de cada proyecto es vital para nuestro trabajo y para la confianza que nuestros clientes depositan en el equipo.</p></article><article className="card"><span className="card__number">Honestidad</span><h3>Hablar con la verdad.</h3><p>Construimos alianzas y relaciones duraderas con conversaciones claras, criterio técnico y transparencia en cada etapa.</p></article><article className="card"><span className="card__number">Lealtad</span><h3>Generar confianza.</h3><p>Buscamos un entorno en el que colaboradores y clientes se sientan valorados, escuchados y respaldados.</p></article></div></div></section>
    <section className="section section--muted"><div className="container"><div className="section-heading"><p className="eyebrow eyebrow--green">Capacidad instalada</p><h2>Equipos y movilidad para responder en campo.</h2></div><div className="equipment-grid"><figure><img src={vehicles} alt="Camionetas de operación de Dimelco" /><figcaption><strong>Movilidad operativa</strong><span>3 camionetas de 1.5 a 4 toneladas y 2 microbuses Chana para 8 personas.</span></figcaption></figure><figure><img src={mixers} alt="Equipos de mezcla y compactación" /><figcaption><strong>Equipos de obra</strong><span>8 mezcladoras, apisonador mecánico, rana compactadora y cortadora de concreto.</span></figcaption></figure><figure><img src={people} alt="Personal técnico de Dimelco" /><figcaption><strong>Herramientas especializadas</strong><span>6 equipos de termofusión para redes de polietileno o PVC de ½ a 2 pulgadas.</span></figcaption></figure></div></div></section>
    <section className="section section--ink"><div className="container cta"><h2>Un aliado técnico para proyectos que deben durar.</h2><Link to="/contacto" className="button button--secondary">Hable con nuestro equipo</Link></div></section>
  </PageShell>;
}
