import PageShell from '../components/PageShell';
import PageHero from '../components/PageHero';
import { company } from '../data/company';

export default function ContactPage() {
  return <PageShell>
    <PageHero tone="light" eyebrow="Contacto" title="Empecemos con una conversación." description="Cuéntenos qué necesita. Nuestro equipo revisará su mensaje y responderá por el canal más adecuado." />
    <section className="section"><div className="container contact-layout"><aside><div className="contact-card"><p className="eyebrow eyebrow--green">Canales directos</p><h2>Información de contacto</h2><dl className="contact-details"><div><dt>Oficina</dt><dd><a href="https://maps.google.com/?q=Calle+2N+1E-07+Barrio+Quinta+Bosch+Cucuta" target="_blank" rel="noreferrer">Calle 2N # 1E-07<br />Barrio Quinta Bosch, Cúcuta<br />Norte de Santander, Colombia</a></dd></div><div><dt>Teléfonos</dt><dd><a href="tel:+573002541830">+57 {company.phones[0]}</a><br /><a href="tel:+573017239148">+57 {company.phones[1]}</a><br /><a href="tel:+575753084">{company.phones[2]}</a></dd></div><div><dt>Correo</dt><dd><a href={`mailto:${company.email}`}>{company.email}</a></dd></div></dl></div><iframe className="map-frame" title="Ubicación de Dimelco S.A.S. en Cúcuta" src="https://www.google.com/maps?q=Calle+2N+1E-07+Barrio+Quinta+Bosch+Cucuta&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></aside><div className="contact-card"><p className="eyebrow eyebrow--green">Escríbanos</p><h2>Háblenos de su proyecto.</h2><p style={{ color: '#647066', lineHeight: 1.65, marginBottom: '28px' }}>Comparta los datos esenciales y nos pondremos en contacto con usted.</p><form className="contact-form" action={`mailto:${company.email}`} method="post" encType="text/plain"><label>Nombre<input name="nombre" autoComplete="given-name" required /></label><label>Empresa<input name="empresa" autoComplete="organization" /></label><label className="full">Correo electrónico<input name="correo" type="email" autoComplete="email" required /></label><label className="full">Tema<select name="tema" defaultValue=""><option value="" disabled>Seleccione una opción</option><option>Solicitud de propuesta</option><option>Consulta técnica</option><option>Oportunidades laborales</option><option>Otro asunto</option></select></label><label className="full">Mensaje<textarea name="mensaje" rows={6} required /></label><div className="full"><button className="button button--primary" type="submit">Enviar mensaje</button></div></form></div></div></section>
  </PageShell>;
}
